<a href="https://colab.research.google.com/github/maly174/Big-Data/blob/main/02_operacje_na_tablicach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.26.4'

# Nowa sekcja

In [12]:
A = np.array([1,2,3])
B = np.array([4,7,9])
print(A, B)

[1 2 3] [4 7 9]


In [13]:
A + B

array([ 5,  9, 12])

In [23]:
np.add(A, B)

array([ 5,  9, 12])

In [14]:
A - B

array([-3, -5, -6])

In [20]:
np.subtract(A, B)

array([-3, -5, -6])

In [18]:
A * B

array([ 4, 14, 27])

In [19]:
np.multiply(A, B)

array([ 4, 14, 27])

In [16]:
A / B

array([0.25      , 0.28571429, 0.33333333])

In [25]:
A+3*B

array([13, 23, 30])

In [27]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [28]:
X * Y

array([[6, 0],
       [2, 0]])

Algebraiczne mnożene maierzy

In [29]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [30]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [31]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [32]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [38]:
 np.random.seed(0)

In [39]:
np.random.randn()

1.764052345967664

In [40]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [41]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [42]:
np.random.rand()

0.1965823616800535

In [43]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [44]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [47]:
np.random.randint(10)

8

In [57]:
np.random.randint(low=10, high=101)

13

In [58]:
np.random.randint(low=10, high=101, size=10)

array([23, 50, 82, 29, 82, 36, 76, 62, 77, 71])

In [62]:
np.random.choice([4, 2, 1, 3, 5])

3

In [64]:
np.random.choice(['python', 'java', 'sql'])

'sql'

In [65]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.random.shuffle(data)

In [68]:
data

array([2, 4, 3, 6, 1, 5, 7, 0, 8, 9])

In [71]:
np.exp(1)

2.718281828459045

In [72]:
np.sqrt(9)

3.0

In [73]:
np.all([2, 3, 1])

True

In [74]:
np.all([2, 3, 0])

False

In [76]:
np.any([0, 1, 0])

True

In [77]:
np.any([0, 0, 0])

False

In [87]:
A = np.random.rand(6)
A

array([0.0191932 , 0.30157482, 0.66017354, 0.29007761, 0.61801543,
       0.4287687 ])

In [79]:
np.argmax(A)

1

In [80]:
A[np.argmax(A)]

0.9560836347232239

In [81]:
np.argmin(A)

3

In [82]:
np.argsort(A)

array([3, 0, 4, 2, 1])

In [83]:
np.max(A)

0.9560836347232239

In [84]:
np.min(A)

0.4238550485581797

In [85]:
np.mean(A)

0.6263292957131336

In [94]:
np.sort(A)



array([0.0191932 , 0.29007761, 0.30157482, 0.4287687 , 0.61801543,
       0.66017354])

In [92]:
np.median(A)

0.36517175881015773

In [96]:
np.std(A)

0.21668212299138445

In [99]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [98]:
A[2]

2

In [100]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [101]:
A[:2]

array([0, 1])

In [103]:
A[[0,2]]

array([0, 2])

In [104]:
A[-1]

19

In [107]:
A[10:15]

array([10, 11, 12, 13, 14])

In [108]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [110]:
A[1]

array([5, 6, 7, 8, 9])

In [111]:
A[:,2]

array([ 2,  7, 12, 17])

In [112]:
A[:, -1]

array([ 4,  9, 14, 19])

In [113]:
A[1,1]

6

In [116]:
A[1,3]

8

In [117]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [118]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [119]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [122]:
for row in A:
  print(row[:3])



[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [125]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [126]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [128]:
A.shape

(4, 5)

In [130]:
A.reshape(5,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [132]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [133]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])