<a href="https://colab.research.google.com/github/maly174/Big-Data/blob/main/02_operacje_na_tablicach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__

'1.26.4'

# Nowa sekcja

In [4]:
A = np.array([1,2,3])
B = np.array([4,7,9])
print(A, B)

[1 2 3] [4 7 9]


In [5]:
A + B

array([ 5,  9, 12])

In [6]:
np.add(A, B)

array([ 5,  9, 12])

In [7]:
A - B

array([-3, -5, -6])

In [8]:
np.subtract(A, B)

array([-3, -5, -6])

In [9]:
A * B

array([ 4, 14, 27])

In [10]:
np.multiply(A, B)

array([ 4, 14, 27])

In [11]:
A / B

array([0.25      , 0.28571429, 0.33333333])

In [12]:
A+3*B

array([13, 23, 30])

In [13]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [14]:
X * Y

array([[6, 0],
       [2, 0]])

Algebraiczne mnożene maierzy

In [15]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [16]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [17]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [18]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [19]:
 np.random.seed(0)

In [20]:
np.random.randn()

1.764052345967664

In [21]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [22]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [23]:
np.random.rand()

0.1965823616800535

In [24]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [25]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [26]:
np.random.randint(10)

3

In [27]:
np.random.randint(low=10, high=101)

56

In [28]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [29]:
np.random.choice([4, 2, 1, 3, 5])

4

In [30]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [31]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.random.shuffle(data)

In [33]:
data

array([6, 9, 1, 5, 0, 7, 3, 4, 8, 2])

In [34]:
np.exp(1)

2.718281828459045

In [35]:
np.sqrt(9)

3.0

In [36]:
np.all([2, 3, 1])

True

In [37]:
np.all([2, 3, 0])

False

In [38]:
np.any([0, 1, 0])

True

In [39]:
np.any([0, 0, 0])

False

In [40]:
A = np.random.rand(6)
A

array([0.29743695, 0.81379782, 0.39650574, 0.8811032 , 0.58127287,
       0.88173536])

In [41]:
np.argmax(A)

5

In [42]:
A[np.argmax(A)]

0.8817353618548528

In [43]:
np.argmin(A)

0

In [44]:
np.argsort(A)

array([0, 2, 4, 1, 3, 5])

In [45]:
np.max(A)

0.8817353618548528

In [46]:
np.min(A)

0.29743695085513366

In [47]:
np.mean(A)

0.6419753238344114

In [48]:
np.sort(A)



array([0.29743695, 0.39650574, 0.58127287, 0.81379782, 0.8811032 ,
       0.88173536])

In [49]:
np.median(A)

0.697535346169168

In [50]:
np.std(A)

0.23339408015360996

In [51]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [52]:
A[2]

2

In [53]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [54]:
A[:2]

array([0, 1])

In [55]:
A[[0,2]]

array([0, 2])

In [56]:
A[-1]

19

In [57]:
A[10:15]

array([10, 11, 12, 13, 14])

In [58]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
A[1]

array([5, 6, 7, 8, 9])

In [60]:
A[:,2]

array([ 2,  7, 12, 17])

In [61]:
A[:, -1]

array([ 4,  9, 14, 19])

In [62]:
A[1,1]

6

In [63]:
A[1,3]

8

In [64]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [65]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [67]:
for row in A:
  print(row[:3])



[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [68]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [69]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
A.shape

(4, 5)

In [71]:
A.reshape(5,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [72]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [75]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [76]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [77]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [79]:
A[np.bitwise_and(A > -5, A < 5)] # A[A > -5 and A < 5] tak nie zadziała musi być z bitwise_and

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])