<a href="https://colab.research.google.com/github/maly174/Big-Data/blob/main/macierze.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__


'1.26.4'

In [6]:
v1 = np.array([0,4])
v1

array([0, 4])

In [7]:
np.linalg.norm(v1)

4.0

In [8]:
v1 = np.array([-1,4])
np.linalg.norm(v1)

4.123105625617661

In [12]:
v3 = np.array([-10,10,13])
np.linalg.norm(v3)

19.209372712298546

In [13]:
p = np.array([3,0])
q = np.array([0,4])
np.linalg.norm(p-q)

5.0

In [16]:
p = np.array([3,0,1])
q = np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

In [18]:
a = np.array([[2,4],[-1,3]])
a

array([[ 2,  4],
       [-1,  3]])

In [20]:
np.linalg.det(a)

9.999999999999998

Ślad maciarzy

In [22]:
np.trace(a)

5

Macierz jednostkowa na przekątnej jedynki

In [27]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna n*n, po pomniżeniu danej macierzy daje macierz jedostkową

In [28]:
a

array([[ 2,  4],
       [-1,  3]])

In [29]:
b = np.linalg.inv(a)
b

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [32]:
np.dot(a, b)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [33]:
np.set_printoptions(precision=4, suppress=True)
np.dot(a, b)

array([[1., 0.],
       [0., 1.]])

In [35]:
np.dot(b,a)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transpoowana (zmaina wiersyz na kolumny)

In [36]:
np.transpose(a)

array([[ 2, -1],
       [ 4,  3]])

In [37]:
a.T

array([[ 2, -1],
       [ 4,  3]])