<a href="https://colab.research.google.com/github/maly174/Big-Data/blob/main/nauka_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__
dir(np)

In [ ]:
help(np.array)

In [7]:
x = np.array([1,3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

In [10]:
x.ndim

1

In [11]:
x.shape

(2,)

In [12]:
x.size

2

In [13]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b.shape



(2, 3)

In [14]:
b.dtype

dtype('int64')

In [19]:
x = np.array([1.23, 2.3232, 2.2323, 5])
print(x)
x.dtype

[1.23   2.3232 2.2323 5.    ]


dtype('float64')

In [24]:
t2 = np.array([[1,2,3],[4,5,6,],[7,8,9],[10,11,12]])
print(t2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
t2.ndim

2

In [26]:
t2.shape

(4, 3)

In [39]:
t3 = np.array(
 [
     [
     [1,2,3,4], [5,6,7,8], [9,10,11,12]
    ],
     [
     [1,2,3,4], [5,6,7,8], [9,10,11,12]
    ],

  ]
  )

In [40]:
print(t3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [41]:
t3.shape

(2, 3, 4)

In [42]:
c1 = np.array([1,2,3,],dtype=complex)
c1


array([1.+0.j, 2.+0.j, 3.+0.j])