<a href="https://colab.research.google.com/github/maly174/Big-Data/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
pd.__version__

'2.2.2'

In [5]:
s = pd.Series([3,2,4,6])
s

0    3
1    2
2    4
3    6
dtype: int64

In [11]:
s = pd.Series(data=[3,2,4,6],index=['a', 'b','c','d'],name='sample')
s

a    3
b    2
c    4
d    6
Name: sample, dtype: int64

In [12]:
import numpy as np

In [13]:
np.nan

nan

In [14]:
s = pd.Series(data=[3,np.nan,4,6],index=['a', 'b','c','d'],name='sample')
s

a    3.0
b    NaN
c    4.0
d    6.0
Name: sample, dtype: float64

In [15]:
s = pd.Series(data=[True, False, True])
s

0     True
1    False
2     True
dtype: bool

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
s = pd.Series(data=np.arange(10,20),index=pd.date_range(start='20200101',periods=10))
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, dtype: int64

In [29]:
pd.date_range(start='2024-01-01 12:00', periods=4, freq='15min')


DatetimeIndex(['2024-01-01 12:00:00', '2024-01-01 12:15:00',
               '2024-01-01 12:30:00', '2024-01-01 12:45:00'],
              dtype='datetime64[ns]', freq='15min')

In [33]:
s = pd.Series(data=np.arange(10,20), index=pd.date_range(start='2024-01-01 12:00', periods=10, freq='15min'))
s

2024-01-01 12:00:00    10
2024-01-01 12:15:00    11
2024-01-01 12:30:00    12
2024-01-01 12:45:00    13
2024-01-01 13:00:00    14
2024-01-01 13:15:00    15
2024-01-01 13:30:00    16
2024-01-01 13:45:00    17
2024-01-01 14:00:00    18
2024-01-01 14:15:00    19
Freq: 15min, dtype: int64

In [34]:
import pandas as pd
import numpy as np

# Parametry
start_date = '2024-01-01 12:00'
frequency = '15min'
data_start = 10
data_end = 20

# Tworzenie danych
values = np.arange(data_start, data_end)
num_periods = len(values)  # Automatyczne określenie liczby okresów

# Tworzenie serii danych
dates = pd.date_range(start=start_date, periods=num_periods, freq=frequency)
series = pd.Series(data=values, index=dates)

print(series)


2024-01-01 12:00:00    10
2024-01-01 12:15:00    11
2024-01-01 12:30:00    12
2024-01-01 12:45:00    13
2024-01-01 13:00:00    14
2024-01-01 13:15:00    15
2024-01-01 13:30:00    16
2024-01-01 13:45:00    17
2024-01-01 14:00:00    18
2024-01-01 14:15:00    19
Freq: 15min, dtype: int64


In [35]:
s.index

DatetimeIndex(['2024-01-01 12:00:00', '2024-01-01 12:15:00',
               '2024-01-01 12:30:00', '2024-01-01 12:45:00',
               '2024-01-01 13:00:00', '2024-01-01 13:15:00',
               '2024-01-01 13:30:00', '2024-01-01 13:45:00',
               '2024-01-01 14:00:00', '2024-01-01 14:15:00'],
              dtype='datetime64[ns]', freq='15min')

In [37]:
list(s.index)

[Timestamp('2024-01-01 12:00:00'),
 Timestamp('2024-01-01 12:15:00'),
 Timestamp('2024-01-01 12:30:00'),
 Timestamp('2024-01-01 12:45:00'),
 Timestamp('2024-01-01 13:00:00'),
 Timestamp('2024-01-01 13:15:00'),
 Timestamp('2024-01-01 13:30:00'),
 Timestamp('2024-01-01 13:45:00'),
 Timestamp('2024-01-01 14:00:00'),
 Timestamp('2024-01-01 14:15:00')]

In [38]:
s.values

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
s.dtypes

dtype('int64')

In [40]:
s.shape

(10,)

In [73]:
p = pd.Series(data={'Apple': 200, 'CD Projekt': 60, 'Amazon': 1900, 'KGHM': np.nan})
p

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [44]:
p['CD Projekt']

60

In [45]:
p[2]

<ipython-input-45-21c545b39f61>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  p[2]


1900

In [46]:
p.count()

3

In [47]:
p.value_counts()

200     1
60      1
1900    1
Name: count, dtype: int64

In [65]:
import numpy as np
array1 = np.zeros(10)
array2 = np.array([1, 2, 3,4,5,6,7,8,9])

s1 = np.concatenate((array1, array2))
p1 = pd.Series(data=s1)
(pd.Series(data=s1)).value_counts()



0.0    10
1.0     1
2.0     1
3.0     1
4.0     1
5.0     1
6.0     1
7.0     1
8.0     1
9.0     1
Name: count, dtype: int64

In [69]:
p1.describe().T

count    19.000000
mean      2.368421
std       3.148377
min       0.000000
25%       0.000000
50%       0.000000
75%       4.500000
max       9.000000
dtype: float64

In [70]:
p.value_counts()

200     1
60      1
1900    1
Name: count, dtype: int64

In [74]:
p.value_counts(dropna=False)

200.0     1
60.0      1
1900.0    1
NaN       1
Name: count, dtype: int64

In [75]:
p.nlargest(2)

Amazon    1900.0
Apple      200.0
dtype: float64

In [76]:
p.nsmallest(2)

CD Projekt     60.0
Apple         200.0
dtype: float64

In [77]:
 p.rank()

Apple         2.0
CD Projekt    1.0
Amazon        3.0
KGHM          NaN
dtype: float64

In [78]:
p.sort_values()

CD Projekt      60.0
Apple          200.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [79]:
p.sort_values(ascending=False)


Amazon        1900.0
Apple          200.0
CD Projekt      60.0
KGHM             NaN
dtype: float64

In [86]:
p.apply(lambda x: x*3.8)

Apple          760.0
CD Projekt     228.0
Amazon        7220.0
KGHM             NaN
dtype: float64

DataFrame

In [88]:
df = pd.DataFrame(data=[12,12,32])
df

0
0  12
1  12
2  32

In [90]:
df = pd.DataFrame(data=[12,12,32], index=['first','second','third'], columns=['col_1'])
df

col_1
first      12
second     12
third      32

In [91]:
df = pd.DataFrame(data={'WIG20': ['PKN ORLEN', 'PKO BP'],
                        'mWIG40': ['Amica', 'Playway']})
df

WIG20   mWIG40
0  PKN ORLEN    Amica
1     PKO BP  Playway

In [97]:
df = pd.DataFrame(data=[[10,12,13],[21,12,10]], index=['first', 'second'], columns=['col_1','col_2','col_3'])
df

col_1  col_2  col_3
first      10     12     13
second     21     12     10

In [98]:
 df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [99]:
df.index

Index(['first', 'second'], dtype='object')

In [100]:
df.values

array([[10, 12, 13],
       [21, 12, 10]])

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, first to second
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_1   2 non-null      int64
 1   col_2   2 non-null      int64
 2   col_3   2 non-null      int64
dtypes: int64(3)
memory usage: 172.0+ bytes


In [103]:
df.describe()

col_1  col_2     col_3
count   2.000000    2.0   2.00000
mean   15.500000   12.0  11.50000
std     7.778175    0.0   2.12132
min    10.000000   12.0  10.00000
25%    12.750000   12.0  10.75000
50%    15.500000   12.0  11.50000
75%    18.250000   12.0  12.25000
max    21.000000   12.0  13.00000

In [104]:
df.describe().T

count  mean       std   min    25%   50%    75%   max
col_1    2.0  15.5  7.778175  10.0  12.75  15.5  18.25  21.0
col_2    2.0  12.0  0.000000  12.0  12.00  12.0  12.00  12.0
col_3    2.0  11.5  2.121320  10.0  10.75  11.5  12.25  13.0

In [105]:
df

col_1  col_2  col_3
first      10     12     13
second     21     12     10

In [106]:
df['col_1']

first     10
second    21
Name: col_1, dtype: int64

In [107]:
type(df['col_1'])

pandas.core.series.Series

In [108]:
df[['col_1']]

col_1
first      10
second     21

In [109]:
type(df[['col_1']])

pandas.core.frame.DataFrame

In [110]:
df.columns = ['a','b','c']
df

a   b   c
first   10  12  13
second  21  12  10

In [111]:
df.b

first     12
second    12
Name: b, dtype: int64

In [113]:
df['d'] = df.a + df.b
df

a   b   c   d
first   10  12  13  22
second  21  12  10  33

In [115]:
df = pd.DataFrame(data=[[10,12,13],[21,12,10]], index=['first', 'second'], columns=['col_1','col_2','col_3'])
df

col_1  col_2  col_3
first      10     12     13
second     21     12     10

In [116]:
df.loc['first']

col_1    10
col_2    12
col_3    13
Name: first, dtype: int64

In [118]:
df.iloc[0]

col_1    10
col_2    12
col_3    13
Name: first, dtype: int64

In [120]:
df.loc['first', 'col_2']

12

In [121]:
df.loc[:, 'col_2']

first     12
second    12
Name: col_2, dtype: int64